name: Publish new plugin version

on: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install
    - name: Commit files
      run: |
        git checkout gh-pages
        cp -r eclipse-solargraph-updatesite/target/repository/. .
        git config --local user.email "PyvesDev@gmail.com"
        git config --local user.name "Pierre-Yves B."
        git add -A
        git commit -m "Added version $(curl --silent https://api.github.com/repos/PyvesB/eclipse-solargraph/releases/latest | grep '\"tag_name\":' | sed -E 's/.*\"([^\"]+)\".*/\1/') to the update site"
        git push https://PyvesB:${{ secrets.GITHUB_TOKEN }}@github.com/PyvesB/eclipse-solargraph.git
